project:
  type: website
  output-dir: docs
  
# Include the html for all pages
website:
  title: "ynot"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    collapse: true
format:
  html:
    theme: lumen
    comments:
      utterances: 
        repo: "fischerpj/ynot"
  
editor: visual
