project:
  type: website
  output-dir: docs
  
# Include the html for all pages
website:
  title: "ynot"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: lumen
    css:   styles.css

editor: visual
